### ISSUE TITLE
Upgrade to v6

### ISSUE THREAD

**Issue by Lucasark** [react-navigation/deep-linking-example#14]
Example is on v5, and need to upgrade to v6

**Comment by WoLewicki** [comment]
This repo seems to be a bit abandoned right now, but we are always open for PRs with such changes. If you have time, feel free to submit one 🚀

**Comment by pavel-rakhmanov** [comment]
Here is a PR with example written with `react-navigation@6.x` https://github.com/react-navigation/deep-linking-example/pull/19 🎁

**Comment by WoLewicki** [comment]
Closing since #29 has been merged 🚀
