### ISSUE TITLE
Deep Linking example with Authentication flows

### ISSUE THREAD

**Issue by losh11** [react-navigation/deep-linking-example#2]
There doesn't seem to be any documentation on the docs or in this example, on how to handle deep linking for applications which use Authentication. In versions of react-navigation prior to v5 there is a [StackOverflow question which solves this](https://stackoverflow.com/questions/54350991/react-navigation-deep-linking-with-authentication), however none of the answers seem to be updated for v5.

The authentication was implemented following the react-navigation docs.

The intended flow is:
URI -> opens app -> opens authentication screen -> auth success = navigate to deep link handling screen

**Comment by losh11** [comment]
Ah I was looking for this once more, I guess there still is no react-navigation deep linking example for v6 with authentication?

**Comment by WoLewicki** [comment]
#29 with navigation v6 has been merged so I'll close it. Feel free to comment if there is something wrong and we can always reopen it then.
