### ISSUE TITLE
Doesn't work on web 

### ISSUE THREAD

**Issue by bpceee** [react-navigation/deep-linking-example#3]
If I refresh on http://localhost:19008/stack/user/Wojciech/22, it goes to http://localhost:19008/stack/home immediately

**Comment by WoLewicki** [comment]
I am sorry but this example is outdated. The API has changed a few times from the beginning. I would love to merge a PR that uses the newest configuration.

**Comment by bpceee** [comment]
@WoLewicki Thanks for your reply. I'm using the latest version, but couldn't make it work on Web. Do you know if it supports Web or not?

**Comment by WoLewicki** [comment]
You can check this link to see what is supported for now: https://reactnavigation.org/docs/web-support
